name: pymateo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - pytorch
  - torchvision
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - nbconvert
  - openpyxl
  - xlrd
  - joblib
  - tqdm
  - pip
  
  # Instalar con pip
  - pip:
    - tensorflow